// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/family.proto

package family

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelativeType int32

const (
	RelativeType_UNKNOWN               RelativeType = 0
	RelativeType_MOTHER                RelativeType = 1
	RelativeType_FATHER                RelativeType = 2
	RelativeType_BROTHER               RelativeType = 3
	RelativeType_SISTER                RelativeType = 4
	RelativeType_GRANDMOTHER           RelativeType = 5
	RelativeType_GRANDFATHER           RelativeType = 6
	RelativeType_AUNT                  RelativeType = 7
	RelativeType_UNCLE                 RelativeType = 8
	RelativeType_COUSIN_BROTHER        RelativeType = 9
	RelativeType_COUSIN_SISTER         RelativeType = 10
	RelativeType_GREAT_GRANDMOTHER     RelativeType = 11
	RelativeType_GREAT_GRANDFATHER     RelativeType = 12
	RelativeType_SECOND_COUSIN_BROTHER RelativeType = 13
	RelativeType_SECOND_COUSIN_SISTER  RelativeType = 14
)

// Enum value maps for RelativeType.
var (
	RelativeType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "MOTHER",
		2:  "FATHER",
		3:  "BROTHER",
		4:  "SISTER",
		5:  "GRANDMOTHER",
		6:  "GRANDFATHER",
		7:  "AUNT",
		8:  "UNCLE",
		9:  "COUSIN_BROTHER",
		10: "COUSIN_SISTER",
		11: "GREAT_GRANDMOTHER",
		12: "GREAT_GRANDFATHER",
		13: "SECOND_COUSIN_BROTHER",
		14: "SECOND_COUSIN_SISTER",
	}
	RelativeType_value = map[string]int32{
		"UNKNOWN":               0,
		"MOTHER":                1,
		"FATHER":                2,
		"BROTHER":               3,
		"SISTER":                4,
		"GRANDMOTHER":           5,
		"GRANDFATHER":           6,
		"AUNT":                  7,
		"UNCLE":                 8,
		"COUSIN_BROTHER":        9,
		"COUSIN_SISTER":         10,
		"GREAT_GRANDMOTHER":     11,
		"GREAT_GRANDFATHER":     12,
		"SECOND_COUSIN_BROTHER": 13,
		"SECOND_COUSIN_SISTER":  14,
	}
)

func (x RelativeType) Enum() *RelativeType {
	p := new(RelativeType)
	*p = x
	return p
}

func (x RelativeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelativeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_family_proto_enumTypes[0].Descriptor()
}

func (RelativeType) Type() protoreflect.EnumType {
	return &file_api_proto_family_proto_enumTypes[0]
}

func (x RelativeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelativeType.Descriptor instead.
func (RelativeType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{0}
}

type Relative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Добавить сюда пир юзера UserPeer
	Type          RelativeType           `protobuf:"varint,2,opt,name=type,proto3,enum=family.RelativeType" json:"type,omitempty"`
	Families      []*Family              `protobuf:"bytes,3,rep,name=families,proto3" json:"families,omitempty"` // Список семей к которым относится родственник
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relative) Reset() {
	*x = Relative{}
	mi := &file_api_proto_family_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relative) ProtoMessage() {}

func (x *Relative) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relative.ProtoReflect.Descriptor instead.
func (*Relative) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{0}
}

func (x *Relative) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Relative) GetType() RelativeType {
	if x != nil {
		return x.Type
	}
	return RelativeType_UNKNOWN
}

func (x *Relative) GetFamilies() []*Family {
	if x != nil {
		return x.Families
	}
	return nil
}

type Family struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surname       string                 `protobuf:"bytes,1,opt,name=surname,proto3" json:"surname,omitempty"`
	Relatives     []*Relative            `protobuf:"bytes,2,rep,name=relatives,proto3" json:"relatives,omitempty"`
	CreatorId     string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Family) Reset() {
	*x = Family{}
	mi := &file_api_proto_family_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{1}
}

func (x *Family) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *Family) GetRelatives() []*Relative {
	if x != nil {
		return x.Relatives
	}
	return nil
}

func (x *Family) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Family) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Family) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surname       string                 `protobuf:"bytes,1,opt,name=surname,proto3" json:"surname,omitempty"`
	CreatorId     string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyRequest) Reset() {
	*x = CreateFamilyRequest{}
	mi := &file_api_proto_family_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyRequest) ProtoMessage() {}

func (x *CreateFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyRequest.ProtoReflect.Descriptor instead.
func (*CreateFamilyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFamilyRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *CreateFamilyRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type CreateFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyResponse) Reset() {
	*x = CreateFamilyResponse{}
	mi := &file_api_proto_family_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyResponse) ProtoMessage() {}

func (x *CreateFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyResponse.ProtoReflect.Descriptor instead.
func (*CreateFamilyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFamilyResponse) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type AddRelativesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Relatives     []*Relative            `protobuf:"bytes,2,rep,name=relatives,proto3" json:"relatives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRelativesRequest) Reset() {
	*x = AddRelativesRequest{}
	mi := &file_api_proto_family_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRelativesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRelativesRequest) ProtoMessage() {}

func (x *AddRelativesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRelativesRequest.ProtoReflect.Descriptor instead.
func (*AddRelativesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{4}
}

func (x *AddRelativesRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *AddRelativesRequest) GetRelatives() []*Relative {
	if x != nil {
		return x.Relatives
	}
	return nil
}

type AddRelativesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRelativesResponse) Reset() {
	*x = AddRelativesResponse{}
	mi := &file_api_proto_family_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRelativesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRelativesResponse) ProtoMessage() {}

func (x *AddRelativesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRelativesResponse.ProtoReflect.Descriptor instead.
func (*AddRelativesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{5}
}

type RemoveRelativeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Relative      *Relative              `protobuf:"bytes,2,opt,name=relative,proto3" json:"relative,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRelativeRequest) Reset() {
	*x = RemoveRelativeRequest{}
	mi := &file_api_proto_family_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRelativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRelativeRequest) ProtoMessage() {}

func (x *RemoveRelativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRelativeRequest.ProtoReflect.Descriptor instead.
func (*RemoveRelativeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveRelativeRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *RemoveRelativeRequest) GetRelative() *Relative {
	if x != nil {
		return x.Relative
	}
	return nil
}

type RemoveRelativeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRelativeResponse) Reset() {
	*x = RemoveRelativeResponse{}
	mi := &file_api_proto_family_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRelativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRelativeResponse) ProtoMessage() {}

func (x *RemoveRelativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRelativeResponse.ProtoReflect.Descriptor instead.
func (*RemoveRelativeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{7}
}

type GetRelativesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelativesRequest) Reset() {
	*x = GetRelativesRequest{}
	mi := &file_api_proto_family_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelativesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelativesRequest) ProtoMessage() {}

func (x *GetRelativesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelativesRequest.ProtoReflect.Descriptor instead.
func (*GetRelativesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{8}
}

func (x *GetRelativesRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *GetRelativesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRelativesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRelativesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relatives     []*Relative            `protobuf:"bytes,1,rep,name=relatives,proto3" json:"relatives,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelativesResponse) Reset() {
	*x = GetRelativesResponse{}
	mi := &file_api_proto_family_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelativesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelativesResponse) ProtoMessage() {}

func (x *GetRelativesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelativesResponse.ProtoReflect.Descriptor instead.
func (*GetRelativesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{9}
}

func (x *GetRelativesResponse) GetRelatives() []*Relative {
	if x != nil {
		return x.Relatives
	}
	return nil
}

func (x *GetRelativesResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetRelativeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelativeRequest) Reset() {
	*x = GetRelativeRequest{}
	mi := &file_api_proto_family_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelativeRequest) ProtoMessage() {}

func (x *GetRelativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelativeRequest.ProtoReflect.Descriptor instead.
func (*GetRelativeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{10}
}

func (x *GetRelativeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRelativeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relative      *Relative              `protobuf:"bytes,1,opt,name=relative,proto3" json:"relative,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelativeResponse) Reset() {
	*x = GetRelativeResponse{}
	mi := &file_api_proto_family_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelativeResponse) ProtoMessage() {}

func (x *GetRelativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_family_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelativeResponse.ProtoReflect.Descriptor instead.
func (*GetRelativeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_family_proto_rawDescGZIP(), []int{11}
}

func (x *GetRelativeResponse) GetRelative() *Relative {
	if x != nil {
		return x.Relative
	}
	return nil
}

var File_api_proto_family_proto protoreflect.FileDescriptor

const file_api_proto_family_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/family.proto\x12\x06family\"y\n" +
	"\bRelative\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.family.RelativeTypeR\x04type\x12*\n" +
	"\bfamilies\x18\x03 \x03(\v2\x0e.family.FamilyR\bfamilies\"\xaf\x01\n" +
	"\x06Family\x12\x18\n" +
	"\asurname\x18\x01 \x01(\tR\asurname\x12.\n" +
	"\trelatives\x18\x02 \x03(\v2\x10.family.RelativeR\trelatives\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"N\n" +
	"\x13CreateFamilyRequest\x12\x18\n" +
	"\asurname\x18\x01 \x01(\tR\asurname\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\"3\n" +
	"\x14CreateFamilyResponse\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"b\n" +
	"\x13AddRelativesRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12.\n" +
	"\trelatives\x18\x02 \x03(\v2\x10.family.RelativeR\trelatives\"\x16\n" +
	"\x14AddRelativesResponse\"b\n" +
	"\x15RemoveRelativeRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12,\n" +
	"\brelative\x18\x02 \x01(\v2\x10.family.RelativeR\brelative\"\x18\n" +
	"\x16RemoveRelativeResponse\"c\n" +
	"\x13GetRelativesRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"Z\n" +
	"\x14GetRelativesResponse\x12.\n" +
	"\trelatives\x18\x01 \x03(\v2\x10.family.RelativeR\trelatives\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\"-\n" +
	"\x12GetRelativeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x13GetRelativeResponse\x12,\n" +
	"\brelative\x18\x01 \x01(\v2\x10.family.RelativeR\brelative*\x8d\x02\n" +
	"\fRelativeType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06MOTHER\x10\x01\x12\n" +
	"\n" +
	"\x06FATHER\x10\x02\x12\v\n" +
	"\aBROTHER\x10\x03\x12\n" +
	"\n" +
	"\x06SISTER\x10\x04\x12\x0f\n" +
	"\vGRANDMOTHER\x10\x05\x12\x0f\n" +
	"\vGRANDFATHER\x10\x06\x12\b\n" +
	"\x04AUNT\x10\a\x12\t\n" +
	"\x05UNCLE\x10\b\x12\x12\n" +
	"\x0eCOUSIN_BROTHER\x10\t\x12\x11\n" +
	"\rCOUSIN_SISTER\x10\n" +
	"\x12\x15\n" +
	"\x11GREAT_GRANDMOTHER\x10\v\x12\x15\n" +
	"\x11GREAT_GRANDFATHER\x10\f\x12\x19\n" +
	"\x15SECOND_COUSIN_BROTHER\x10\r\x12\x18\n" +
	"\x14SECOND_COUSIN_SISTER\x10\x0e2\x89\x03\n" +
	"\rFamilyService\x12I\n" +
	"\fCreateFamily\x12\x1b.family.CreateFamilyRequest\x1a\x1c.family.CreateFamilyResponse\x12I\n" +
	"\fAddRelatives\x12\x1b.family.AddRelativesRequest\x1a\x1c.family.AddRelativesResponse\x12O\n" +
	"\x0eRemoveRelative\x12\x1d.family.RemoveRelativeRequest\x1a\x1e.family.RemoveRelativeResponse\x12I\n" +
	"\fGetRelatives\x12\x1b.family.GetRelativesRequest\x1a\x1c.family.GetRelativesResponse\x12F\n" +
	"\vGetRelative\x12\x1a.family.GetRelativeRequest\x1a\x1b.family.GetRelativeResponseB\x12Z\x10api/proto/familyb\x06proto3"

var (
	file_api_proto_family_proto_rawDescOnce sync.Once
	file_api_proto_family_proto_rawDescData []byte
)

func file_api_proto_family_proto_rawDescGZIP() []byte {
	file_api_proto_family_proto_rawDescOnce.Do(func() {
		file_api_proto_family_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_family_proto_rawDesc), len(file_api_proto_family_proto_rawDesc)))
	})
	return file_api_proto_family_proto_rawDescData
}

var file_api_proto_family_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_family_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_family_proto_goTypes = []any{
	(RelativeType)(0),              // 0: family.RelativeType
	(*Relative)(nil),               // 1: family.Relative
	(*Family)(nil),                 // 2: family.Family
	(*CreateFamilyRequest)(nil),    // 3: family.CreateFamilyRequest
	(*CreateFamilyResponse)(nil),   // 4: family.CreateFamilyResponse
	(*AddRelativesRequest)(nil),    // 5: family.AddRelativesRequest
	(*AddRelativesResponse)(nil),   // 6: family.AddRelativesResponse
	(*RemoveRelativeRequest)(nil),  // 7: family.RemoveRelativeRequest
	(*RemoveRelativeResponse)(nil), // 8: family.RemoveRelativeResponse
	(*GetRelativesRequest)(nil),    // 9: family.GetRelativesRequest
	(*GetRelativesResponse)(nil),   // 10: family.GetRelativesResponse
	(*GetRelativeRequest)(nil),     // 11: family.GetRelativeRequest
	(*GetRelativeResponse)(nil),    // 12: family.GetRelativeResponse
}
var file_api_proto_family_proto_depIdxs = []int32{
	0,  // 0: family.Relative.type:type_name -> family.RelativeType
	2,  // 1: family.Relative.families:type_name -> family.Family
	1,  // 2: family.Family.relatives:type_name -> family.Relative
	1,  // 3: family.AddRelativesRequest.relatives:type_name -> family.Relative
	1,  // 4: family.RemoveRelativeRequest.relative:type_name -> family.Relative
	1,  // 5: family.GetRelativesResponse.relatives:type_name -> family.Relative
	1,  // 6: family.GetRelativeResponse.relative:type_name -> family.Relative
	3,  // 7: family.FamilyService.CreateFamily:input_type -> family.CreateFamilyRequest
	5,  // 8: family.FamilyService.AddRelatives:input_type -> family.AddRelativesRequest
	7,  // 9: family.FamilyService.RemoveRelative:input_type -> family.RemoveRelativeRequest
	9,  // 10: family.FamilyService.GetRelatives:input_type -> family.GetRelativesRequest
	11, // 11: family.FamilyService.GetRelative:input_type -> family.GetRelativeRequest
	4,  // 12: family.FamilyService.CreateFamily:output_type -> family.CreateFamilyResponse
	6,  // 13: family.FamilyService.AddRelatives:output_type -> family.AddRelativesResponse
	8,  // 14: family.FamilyService.RemoveRelative:output_type -> family.RemoveRelativeResponse
	10, // 15: family.FamilyService.GetRelatives:output_type -> family.GetRelativesResponse
	12, // 16: family.FamilyService.GetRelative:output_type -> family.GetRelativeResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_family_proto_init() }
func file_api_proto_family_proto_init() {
	if File_api_proto_family_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_family_proto_rawDesc), len(file_api_proto_family_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_family_proto_goTypes,
		DependencyIndexes: file_api_proto_family_proto_depIdxs,
		EnumInfos:         file_api_proto_family_proto_enumTypes,
		MessageInfos:      file_api_proto_family_proto_msgTypes,
	}.Build()
	File_api_proto_family_proto = out.File
	file_api_proto_family_proto_goTypes = nil
	file_api_proto_family_proto_depIdxs = nil
}
